# Generated by Django 5.1.2 on 2025-09-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('spareparts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='turns', to='services.service')),
                ('spareparts', models.ManyToManyField(blank=True, related_name='turns', to='spareparts.sparepart')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='vehicles.vehicle')),
            ],
        ),
    ]
